name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1  # v2 does not have submodules option now
        with:
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.49.2'

      - name: Build
        run: hugo

      - name: Purifycss
        run: |
          sudo npm install -g purify-css

          CSS_FILE="./public/styles.css"
          BOOTSTRAP_CSS="./public/css/bootstrap.min.css"

          find public/ -name "*html" -type f | \
            xargs purifycss "$CSS_FILE" --info --min --out "$CSS_FILE"

          find public/ -name "*html" -type f | \
            xargs purifycss "$BOOTSTRAP_CSS" --info --min --out "$BOOTSTRAP_CSS"


      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
